os:
  - linux

env:
  - DOCKER_COMPOSE_VERSION=2.2

language: php

php:
  - '7.4'

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install stable
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

install:
  - sudo apt-get update
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose exec app php artisan migrate
  - docker-compose exec app php artisan key:generate
  - docker-compose exec app php artisan passport:install
  - docker-compose exec app php artisan db:seed
  - docker-compose exec app vendor/bin/phpunit
  - npm run production

after_script:
  - docker-compose stop
  - docker-compose rm -f