/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "l5-swagger.default.api": [],
    "l5-swagger.default.docs": [],
    "l5-swagger.default.asset": [
        {
            "name": "asset",
            "required": true
        }
    ],
    "l5-swagger.default.oauth2_callback": [],
    "api.v1.apple-maps.token": [],
    "api.v1.apple-maps.geocode": [],
    "api.v1.apple-maps.annotation.preview": [],
    "api.v1.pages.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.admin.page.blocks.index": [
        {
            "name": "pageId",
            "required": true
        }
    ],
    "api.v1.admin.page-blocks.children": [
        {
            "name": "pageBlockId",
            "required": true
        }
    ],
    "admin.pages.blocks.store": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.pages.blocks.order": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.blocks.show": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.blocks.hide": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.blocks.publish": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.blocks.unpublish": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.blocks.expire": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.blocks.unexpire": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.blocks.delete": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.blocks.restore": [
        {
            "name": "anyblock",
            "required": true
        }
    ],
    "admin.pages.delete": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.pages.restore": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.pages.publish": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.pages.unpublish": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.pages.archive": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.pages.unarchive": [
        {
            "name": "anypage",
            "required": true
        }
    ],
    "admin.editor.menu.index": [],
    "admin.page-blocks.children.order": [
        {
            "name": "anypageblock",
            "required": true
        }
    ],
    "boost.browser-logs": [],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "passport.token": [],
    "passport.authorizations.authorize": [],
    "passport.token.refresh": [],
    "passport.authorizations.approve": [],
    "passport.authorizations.deny": [],
    "passport.tokens.index": [],
    "passport.tokens.destroy": [
        {
            "name": "token_id",
            "required": true
        }
    ],
    "passport.clients.index": [],
    "passport.clients.store": [],
    "passport.clients.update": [
        {
            "name": "client_id",
            "required": true
        }
    ],
    "passport.clients.destroy": [
        {
            "name": "client_id",
            "required": true
        }
    ],
    "passport.scopes.index": [],
    "passport.personal.tokens.index": [],
    "passport.personal.tokens.store": [],
    "passport.personal.tokens.destroy": [
        {
            "name": "token_id",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "festival.v1.events.index": [],
    "festival.v1.events.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.content": [],
    "festival.v1.event.page.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.locations.index": [],
    "festival.v1.locations.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.map.venues.index": [],
    "festival.v1.map.venues.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.pages.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.news.index": [],
    "festival.v1.feeds.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.feeds.posts.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.posts.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "festival.v1.stream.index": [],
    "festival.v1.update.app.ios": [],
    "v2.tracker.index": [],
    "home": [],
    "apps.ios": [],
    "apps.android": [],
    "legal.privacy": [],
    "legal.tac": [],
    "legal.imprint": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "api.v1.events.index": [],
    "api.v1.events.show": [
        {
            "name": "event",
            "required": true
        }
    ],
    "events.index": [],
    "events.show": [
        {
            "name": "event",
            "required": true,
            "binding": "id"
        }
    ],
    "events.place.update": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "events.edit": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "events.venue.edit": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "events.update": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "events.store": [],
    "events.archive": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "events.unarchive": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "events.publish": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "events.unpublish": [
        {
            "name": "anyevent",
            "required": true
        }
    ],
    "api.locations.index": [],
    "api.locations.show": [
        {
            "name": "location",
            "required": true,
            "binding": "id"
        }
    ],
    "locations.create": [],
    "locations.store": [],
    "locations.edit": [
        {
            "name": "location",
            "required": true,
            "binding": "id"
        }
    ],
    "locations.update": [
        {
            "name": "location",
            "required": true,
            "binding": "id"
        }
    ],
    "locations.destroy": [
        {
            "name": "location",
            "required": true,
            "binding": "id"
        }
    ],
    "api.management.index": [],
    "api.management.store": [],
    "api.management.show": [
        {
            "name": "management",
            "required": true
        }
    ],
    "api.management.update": [
        {
            "name": "management",
            "required": true
        }
    ],
    "api.management.destroy": [
        {
            "name": "management",
            "required": true
        }
    ],
    "organisations.create": [],
    "organisations.store": [],
    "organisations.show": [
        {
            "name": "organisation",
            "required": true,
            "binding": "slug"
        }
    ],
    "organisations.edit": [
        {
            "name": "organisation",
            "required": true,
            "binding": "slug"
        }
    ],
    "organisations.events.index": [
        {
            "name": "organisation",
            "required": true,
            "binding": "slug"
        }
    ],
    "organisations.index": [],
    "api.v1.api.v1.radio-broadcasts.index": [],
    "api.v1.api.v1.radio-broadcasts.show": [
        {
            "name": "radioBroadcast",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.feeds.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.feeds.posts.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.posts.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "news.index": [],
    "news.show": [
        {
            "name": "anypost",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.index": [],
    "posts.create": [],
    "posts.edit": [
        {
            "name": "anypost",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.store": [],
    "posts.update": [
        {
            "name": "anypost",
            "required": true,
            "binding": "id"
        }
    ],
    "posts.publish": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "posts.unpublish": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "posts.archive": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "posts.unarchive": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "feeds.index": [],
    "feeds.create": [],
    "feeds.store": [],
    "feeds.edit": [
        {
            "name": "anyfeed",
            "required": true,
            "binding": "id"
        }
    ],
    "feeds.update": [
        {
            "name": "anyfeed",
            "required": true,
            "binding": "id"
        }
    ],
    "feeds.destroy": [
        {
            "name": "anyfeed",
            "required": true,
            "binding": "id"
        }
    ],
    "feeds.restore": [
        {
            "name": "anyfeed",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.posts.store": [],
    "admin.posts.publish": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "admin.posts.unpublish": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "admin.posts.archive": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "admin.posts.unarchive": [
        {
            "name": "anypost",
            "required": true
        }
    ],
    "api.v1.parking-areas.dashboard": [],
    "api.v1.parking-areas.index": [],
    "api.v1.parking-areas.show": [
        {
            "name": "parkingArea",
            "required": true,
            "binding": "id"
        }
    ],
    "parking-areas.index": [],
    "parking-areas.show": [
        {
            "name": "parkingArea",
            "required": true,
            "binding": "slug"
        }
    ],
    "api.v1.rubbish.streets.pickups.index": [
        {
            "name": "street",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.rubbish.streets.index": [],
    "api.v2.rubbish.streets.pickups.index": [
        {
            "name": "street",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v2.rubbish.streets.index": [],
    "rubbish.index": [],
    "rubbish.show": [
        {
            "name": "street",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
